default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  advisory_locks: false
